# Generated by Django 5.1.4 on 2026-09-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='analysis_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='analysis_stage',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='analysis_status',
            field=models.CharField(choices=[('NONE', 'None'), ('IMPORTING', 'Importing'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('NO_MANIFEST', 'No Manifest'), ('PARTIAL', 'Partial Analysis'), ('FAILED', 'Failed')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='detected_files',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='detected_manifests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='github_commit_sha',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='github_default_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='github_owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Upload'), ('github', 'GitHub Repository')], default='manual', max_length=20),
        ),
    ]
