# Generated by Django 5.1.4 on 2026-09-14 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.BigIntegerField()),
                ('github_username', models.CharField(max_length=150)),
                ('access_token', models.TextField()),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
                'ordering': ['-connected_at'],
            },
        ),
    ]
