# Generated by Django 5.1.4 on 2026-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubconnection',
            name='github_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
