# Generated by Django 5.1.4 on 2026-09-09 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('version_spec', models.CharField(blank=True, max_length=100)),
                ('ecosystem', models.CharField(choices=[('npm', 'npm (Node.js)'), ('PyPI', 'PyPI (Python)'), ('Maven', 'Maven (Java)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_direct', models.BooleanField(default=True)),
                ('dependency_type', models.CharField(choices=[('direct', 'Direct'), ('dev', 'Development'), ('transitive', 'Transitive'), ('unknown', 'Unknown')], default='direct', max_length=20)),
                ('license', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('license_category', models.CharField(blank=True, default='UNKNOWN', max_length=50)),
                ('license_source', models.CharField(blank=True, max_length=50)),
                ('maintenance_status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOW_ACTIVITY', 'Low Activity'), ('STALE', 'Stale'), ('ABANDONED', 'Abandoned'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('last_release_date', models.DateField(blank=True, null=True)),
                ('release_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('homepage', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='scans.scan')),
            ],
            options={
                'verbose_name': 'Dependency',
                'verbose_name_plural': 'Dependencies',
                'ordering': ['-risk_score', 'name'],
                'unique_together': {('scan', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DependencyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='dependencies.dependency')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dependencies.dependency')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='scans.scan')),
            ],
            options={
                'verbose_name': 'Dependency Relationship',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
