# Generated by Django 5.1.4 on 2026-09-09 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('package.json', 'package.json (npm)'), ('requirements.txt', 'requirements.txt (PyPI)'), ('pom.xml', 'pom.xml (Maven)'), ('github', 'GitHub Repository')], max_length=30)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='scans/')),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='projects.project')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
