# Generated by Django 5.1.4 on 2026-09-09 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SECURITY', 'Security'), ('LICENSE', 'License'), ('MAINTENANCE', 'Maintenance'), ('DEPENDENCY', 'Dependency')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='dependencies.dependency')),
            ],
            options={
                'verbose_name': 'Risk Finding',
                'ordering': ['category', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('OSV', 'OSV (Open Source Vulnerabilities)'), ('NVD', 'NVD (National Vulnerability Database)'), ('GITHUB', 'GitHub Security Advisory'), ('MANUAL', 'Manual')], default='OSV', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('affected_versions', models.TextField(blank=True)),
                ('fixed_version', models.CharField(blank=True, max_length=100)),
                ('references', models.JSONField(blank=True, default=list)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dependencies.dependency')),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-cvss_score', 'severity'],
                'unique_together': {('dependency', 'identifier')},
            },
        ),
    ]
